SAVIYNT_SERVER_URL = "https://dev-scrum-conn.saviyntcloud.com"
SAVIYNT_USERNAME   = "admin"
SAVIYNT_PASSWORD = "Not4password#"
PASSWORD = "MyOffice12#"
IP_ADDRESS="saviyntdc01.saviyntlabs.org"
LDAP_PORT="389"
LDAP_PROTOCOL="LDAP"
BIND_USER = "CN=POC Admin,CN=Users,DC=saviyntlabs,DC=org"
DOMAIN="DC=saviyntlabs,DC=org"
BASE_CONTAINER="CN=Users,DC=saviyntlabs,DC=org"
